ALTER TABLE "Player" ALTER COLUMN "joinedDate" DROP NOT NULL;
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "lastPlayedAt" DROP NOT NULL;
ALTER TABLE "Match" ALTER COLUMN "scheduledAt" DROP NOT NULL;
ALTER TABLE "Match" ALTER COLUMN "createdAt" DROP NOT NULL;
