CREATE TABLE IF NOT EXISTS "user" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "emailVerified" BOOLEAN NOT NULL,
  "image" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "role" TEXT,
  "banned" BOOLEAN,
  "banReason" TEXT,
  "banExpires" TIMESTAMPTZ,
  "twoFactorEnabled" BOOLEAN
);
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL PRIMARY KEY;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL UNIQUE;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN NOT NULL;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "role" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "banned" BOOLEAN;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "banReason" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "banExpires" TIMESTAMPTZ;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN;

CREATE TABLE IF NOT EXISTS "session" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "token" TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  "impersonatedBy" TEXT
);
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL PRIMARY KEY;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMPTZ NOT NULL;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "token" TEXT NOT NULL UNIQUE;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "impersonatedBy" TEXT;
CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session"("userId");

CREATE TABLE IF NOT EXISTS "account" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMPTZ,
  "refreshTokenExpiresAt" TIMESTAMPTZ,
  "scope" TEXT,
  "password" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL
);
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL PRIMARY KEY;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "accountId" TEXT NOT NULL;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "providerId" TEXT NOT NULL;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "accessToken" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "refreshToken" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "idToken" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "accessTokenExpiresAt" TIMESTAMPTZ;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "refreshTokenExpiresAt" TIMESTAMPTZ;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "scope" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL;
CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account"("userId");

CREATE TABLE IF NOT EXISTS "verification" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "identifier" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL PRIMARY KEY;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "identifier" TEXT NOT NULL;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "value" TEXT NOT NULL;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMPTZ NOT NULL;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification"("identifier");

CREATE TABLE IF NOT EXISTS "twoFactor" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "secret" TEXT NOT NULL,
  "backupCodes" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  "verified" BOOLEAN,
  "failedVerificationCount" INTEGER,
  "lockedUntil" TIMESTAMPTZ
);
ALTER TABLE "twoFactor" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL PRIMARY KEY;
ALTER TABLE "twoFactor" ADD COLUMN IF NOT EXISTS "secret" TEXT NOT NULL;
ALTER TABLE "twoFactor" ADD COLUMN IF NOT EXISTS "backupCodes" TEXT NOT NULL;
ALTER TABLE "twoFactor" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "twoFactor" ADD COLUMN IF NOT EXISTS "verified" BOOLEAN;
ALTER TABLE "twoFactor" ADD COLUMN IF NOT EXISTS "failedVerificationCount" INTEGER;
ALTER TABLE "twoFactor" ADD COLUMN IF NOT EXISTS "lockedUntil" TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS "twoFactor_secret_idx" ON "twoFactor"("secret");
CREATE INDEX IF NOT EXISTS "twoFactor_userId_idx" ON "twoFactor"("userId");

CREATE TABLE IF NOT EXISTS "passkey" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT,
  "publicKey" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  "credentialID" TEXT NOT NULL,
  "counter" INTEGER NOT NULL,
  "deviceType" TEXT NOT NULL,
  "backedUp" BOOLEAN NOT NULL,
  "transports" TEXT,
  "createdAt" TIMESTAMPTZ,
  "aaguid" TEXT
);
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL PRIMARY KEY;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "publicKey" TEXT NOT NULL;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "credentialID" TEXT NOT NULL;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "counter" INTEGER NOT NULL;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "deviceType" TEXT NOT NULL;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "backedUp" BOOLEAN NOT NULL;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "transports" TEXT;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ;
ALTER TABLE "passkey" ADD COLUMN IF NOT EXISTS "aaguid" TEXT;
CREATE INDEX IF NOT EXISTS "passkey_userId_idx" ON "passkey"("userId");
CREATE INDEX IF NOT EXISTS "passkey_credentialID_idx" ON "passkey"("credentialID");

CREATE TABLE IF NOT EXISTS "$FILES" (
  "id" TEXT PRIMARY KEY,
  "mimeType" TEXT NOT NULL,
  "fileName" TEXT NOT NULL,
  "data" TEXT NOT NULL
);
ALTER TABLE "$FILES" ADD COLUMN IF NOT EXISTS "id" TEXT PRIMARY KEY;
ALTER TABLE "$FILES" ADD COLUMN IF NOT EXISTS "mimeType" TEXT NOT NULL;
ALTER TABLE "$FILES" ADD COLUMN IF NOT EXISTS "fileName" TEXT NOT NULL;
ALTER TABLE "$FILES" ADD COLUMN IF NOT EXISTS "data" TEXT NOT NULL;

CREATE TABLE IF NOT EXISTS "_outbox" (
  "id" TEXT PRIMARY KEY,
  "notification" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "recipient" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "html" TEXT NOT NULL DEFAULT '',
  "inReplyTo" TEXT NOT NULL DEFAULT '',
  "attachmentName" TEXT NOT NULL DEFAULT '',
  "attachmentBody" TEXT NOT NULL DEFAULT '',
  "createdAt" TEXT NOT NULL,
  "sentAt" TEXT NOT NULL DEFAULT '',
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "lastError" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "id" TEXT PRIMARY KEY;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "notification" TEXT NOT NULL;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "channel" TEXT NOT NULL;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "recipient" TEXT NOT NULL;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "subject" TEXT NOT NULL;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "body" TEXT NOT NULL;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "html" TEXT NOT NULL DEFAULT '';
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "inReplyTo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "attachmentName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "attachmentBody" TEXT NOT NULL DEFAULT '';
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "createdAt" TEXT NOT NULL;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "sentAt" TEXT NOT NULL DEFAULT '';
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "attempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "_outbox" ADD COLUMN IF NOT EXISTS "lastError" TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS "creator_games" (
  "userId" TEXT NOT NULL,
  "gameTypeId" TEXT PRIMARY KEY REFERENCES "GameType"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IF NOT EXISTS "creator_games_user_idx" ON "creator_games"("userId");

CREATE TABLE IF NOT EXISTS "creator_players" (
  "userId" TEXT NOT NULL,
  "playerId" TEXT PRIMARY KEY REFERENCES "Player"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IF NOT EXISTS "creator_players_user_idx" ON "creator_players"("userId");

CREATE TABLE IF NOT EXISTS "creator_matches" (
  "userId" TEXT NOT NULL,
  "matchId" TEXT PRIMARY KEY REFERENCES "Match"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IF NOT EXISTS "creator_matches_user_idx" ON "creator_matches"("userId");

CREATE TABLE IF NOT EXISTS "creator_leaderboards" (
  "userId" TEXT NOT NULL,
  "leaderboardEntryId" TEXT PRIMARY KEY REFERENCES "LeaderboardEntry"("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IF NOT EXISTS "creator_leaderboards_user_idx" ON "creator_leaderboards"("userId");

CREATE TABLE IF NOT EXISTS "app_role" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "isPredefined" BOOLEAN NOT NULL
);
ALTER TABLE "app_role" ADD COLUMN IF NOT EXISTS "id" TEXT PRIMARY KEY;
ALTER TABLE "app_role" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL UNIQUE;
ALTER TABLE "app_role" ADD COLUMN IF NOT EXISTS "isPredefined" BOOLEAN NOT NULL;
INSERT INTO "app_role" ("id", "name", "isPredefined") VALUES ('admin', 'admin', true) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "app_role" ("id", "name", "isPredefined") VALUES ('unassigned', 'unassigned', true) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "app_role" ("id", "name", "isPredefined") VALUES ('guest', 'guest', true) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "app_role" ("id", "name", "isPredefined") VALUES ('player', 'player', false) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "app_role" ("id", "name", "isPredefined") VALUES ('scorekeeper', 'scorekeeper', false) ON CONFLICT ("id") DO NOTHING;

CREATE TABLE IF NOT EXISTS "app_user_role" (
  "userId" TEXT NOT NULL,
  "roleId" TEXT NOT NULL REFERENCES "app_role"("id") DEFERRABLE INITIALLY IMMEDIATE,
  PRIMARY KEY ("userId", "roleId")
);
ALTER TABLE "app_user_role" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "app_user_role" ADD COLUMN IF NOT EXISTS "roleId" TEXT NOT NULL REFERENCES "app_role"("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE IF NOT EXISTS "app_config" (
  "id" TEXT PRIMARY KEY,
  "requireEmailVerification" BOOLEAN NOT NULL DEFAULT TRUE,
  "allowAccountDeletion" BOOLEAN NOT NULL DEFAULT TRUE,
  "inviteOnly" BOOLEAN NOT NULL DEFAULT FALSE,
  "showStaleData" BOOLEAN NOT NULL DEFAULT FALSE,
  "aiConsentRequired" BOOLEAN NOT NULL DEFAULT TRUE
);
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "id" TEXT PRIMARY KEY;
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "requireEmailVerification" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "allowAccountDeletion" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "inviteOnly" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "showStaleData" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "app_config" ADD COLUMN IF NOT EXISTS "aiConsentRequired" BOOLEAN NOT NULL DEFAULT TRUE;
INSERT INTO "app_config" ("id", "requireEmailVerification", "allowAccountDeletion", "inviteOnly", "showStaleData", "aiConsentRequired") VALUES ('singleton', TRUE, TRUE, FALSE, FALSE, TRUE) ON CONFLICT ("id") DO NOTHING;

CREATE TABLE IF NOT EXISTS "app_invitation" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL,
  "roleId" TEXT NOT NULL DEFAULT '',
  "token" TEXT NOT NULL UNIQUE,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "invitedBy" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE "app_invitation" ADD COLUMN IF NOT EXISTS "id" TEXT PRIMARY KEY;
ALTER TABLE "app_invitation" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL;
ALTER TABLE "app_invitation" ADD COLUMN IF NOT EXISTS "roleId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "app_invitation" ADD COLUMN IF NOT EXISTS "token" TEXT NOT NULL UNIQUE;
ALTER TABLE "app_invitation" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMPTZ NOT NULL;
ALTER TABLE "app_invitation" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "app_invitation" ADD COLUMN IF NOT EXISTS "invitedBy" TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS "app_privacy_inquiry" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL DEFAULT '',
  "email" TEXT NOT NULL DEFAULT '',
  "kind" TEXT NOT NULL DEFAULT 'access',
  "attributes" TEXT NOT NULL DEFAULT '{}',
  "verified" BOOLEAN NOT NULL DEFAULT FALSE,
  "verifyToken" TEXT NOT NULL DEFAULT '',
  "status" TEXT NOT NULL DEFAULT 'pending',
  "requestedAt" TEXT NOT NULL DEFAULT '',
  "resolution" TEXT NOT NULL DEFAULT '',
  "resolvedAt" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "id" TEXT PRIMARY KEY;
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'access';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "attributes" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "verified" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "verifyToken" TEXT NOT NULL DEFAULT '';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "requestedAt" TEXT NOT NULL DEFAULT '';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "resolution" TEXT NOT NULL DEFAULT '';
ALTER TABLE "app_privacy_inquiry" ADD COLUMN IF NOT EXISTS "resolvedAt" TEXT NOT NULL DEFAULT '';


ALTER TABLE "GameType" ALTER COLUMN "name" SET DEFAULT '';
ALTER TABLE "GameType" ALTER COLUMN "category" SET DEFAULT '';
ALTER TABLE "GameType" ALTER COLUMN "rulesVariant" SET DEFAULT '';
ALTER TABLE "GameType" ALTER COLUMN "defaultRating" SET DEFAULT 0;
ALTER TABLE "GameType" ALTER COLUMN "description" SET DEFAULT '';
ALTER TABLE "Player" ALTER COLUMN "nickname" SET DEFAULT '';
ALTER TABLE "Player" ALTER COLUMN "fullName" SET DEFAULT '';
ALTER TABLE "Player" ALTER COLUMN "emailAddress" SET DEFAULT '';
ALTER TABLE "Player" ALTER COLUMN "avatar" SET DEFAULT '';
ALTER TABLE "Player" ALTER COLUMN "bio" SET DEFAULT '';
ALTER TABLE "Player" ALTER COLUMN "joinedDate" DROP NOT NULL;
ALTER TABLE "Player" ALTER COLUMN "userAccountId" SET DEFAULT '';
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "playerId" SET DEFAULT '';
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "gameId" SET DEFAULT '';
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "rating" SET DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "matchesPlayed" SET DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "wins" SET DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "losses" SET DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "draws" SET DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ALTER COLUMN "lastPlayedAt" DROP NOT NULL;
ALTER TABLE "Match" ALTER COLUMN "gameId" SET DEFAULT '';
ALTER TABLE "Match" ALTER COLUMN "playerOneId" SET DEFAULT '';
ALTER TABLE "Match" ALTER COLUMN "playerTwoId" SET DEFAULT '';
ALTER TABLE "Match" ALTER COLUMN "scheduledAt" DROP NOT NULL;
ALTER TABLE "Match" ALTER COLUMN "status" SET DEFAULT '';
ALTER TABLE "Match" ALTER COLUMN "outcome" SET DEFAULT '';
ALTER TABLE "Match" ALTER COLUMN "playerOneScore" SET DEFAULT 0;
ALTER TABLE "Match" ALTER COLUMN "playerTwoScore" SET DEFAULT 0;
ALTER TABLE "Match" ALTER COLUMN "playerOneRatingDelta" SET DEFAULT 0;
ALTER TABLE "Match" ALTER COLUMN "playerTwoRatingDelta" SET DEFAULT 0;
ALTER TABLE "Match" ALTER COLUMN "notes" SET DEFAULT '';
ALTER TABLE "Match" ALTER COLUMN "recordedById" SET DEFAULT '';
ALTER TABLE "Match" ALTER COLUMN "createdAt" DROP NOT NULL;

