ALTER TABLE "GameType" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GameType" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT '' CHECK ("category" IN ('', 'chess', 'billiards', 'tableTennis', 'darts', 'boardGames', 'cardGames', 'custom'));
SELECT pg_temp.replace_checks('GameType', 'category', 'CHECK ("category" IN ('''', ''chess'', ''billiards'', ''tableTennis'', ''darts'', ''boardGames'', ''cardGames'', ''custom''))');
ALTER TABLE "GameType" ADD COLUMN IF NOT EXISTS "rulesVariant" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GameType" ADD COLUMN IF NOT EXISTS "defaultRating" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "GameType" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
SELECT pg_temp.drop_stray_unique_indexes('GameType', 'ux_GameType_', ARRAY[]::text[]);
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "nickname" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "fullName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "emailAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "avatar" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "bio" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "joinedDate" DATE;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "userAccountId" TEXT NOT NULL DEFAULT '';
SELECT pg_temp.drop_stray_unique_indexes('Player', 'ux_Player_', ARRAY['ux_Player_nickname', 'ux_Player_emailAddress']::text[]);
SELECT pg_temp.require_unique('Player', ARRAY['nickname']::text[], ' WHERE "nickname" <> ''''');
CREATE UNIQUE INDEX IF NOT EXISTS "ux_Player_nickname" ON "Player" ("nickname") WHERE "nickname" <> '';
SELECT pg_temp.require_unique('Player', ARRAY['emailAddress']::text[], ' WHERE "emailAddress" <> ''''');
CREATE UNIQUE INDEX IF NOT EXISTS "ux_Player_emailAddress" ON "Player" ("emailAddress") WHERE "emailAddress" <> '';
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "playerId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "gameId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "rating" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "matchesPlayed" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "wins" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "losses" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "draws" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "LeaderboardEntry" ADD COLUMN IF NOT EXISTS "lastPlayedAt" TIMESTAMP WITH TIME ZONE;
SELECT pg_temp.drop_stray_unique_indexes('LeaderboardEntry', 'ux_LeaderboardEntry_', ARRAY['ux_LeaderboardEntry_playerId_gameId']::text[]);
SELECT pg_temp.require_unique('LeaderboardEntry', ARRAY['playerId', 'gameId']::text[], ' WHERE "playerId" <> '''' AND "gameId" <> ''''');
CREATE UNIQUE INDEX IF NOT EXISTS "ux_LeaderboardEntry_playerId_gameId" ON "LeaderboardEntry" ("playerId", "gameId") WHERE "playerId" <> '' AND "gameId" <> '';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "gameId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "playerOneId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "playerTwoId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "scheduledAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT '' CHECK ("status" IN ('', 'scheduled', 'inProgress', 'completed', 'disputed', 'cancelled'));
SELECT pg_temp.replace_checks('Match', 'status', 'CHECK ("status" IN ('''', ''scheduled'', ''inProgress'', ''completed'', ''disputed'', ''cancelled''))');
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "outcome" TEXT NOT NULL DEFAULT '' CHECK ("outcome" IN ('', 'playerOneWin', 'playerTwoWin', 'draw'));
SELECT pg_temp.replace_checks('Match', 'outcome', 'CHECK ("outcome" IN ('''', ''playerOneWin'', ''playerTwoWin'', ''draw''))');
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "playerOneScore" NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "playerTwoScore" NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "playerOneRatingDelta" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "playerTwoRatingDelta" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "notes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "recordedById" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE;
SELECT pg_temp.drop_stray_unique_indexes('Match', 'ux_Match_', ARRAY[]::text[]);
SELECT pg_temp.add_missing_column('LeaderboardEntry', 'playerId$reference', ARRAY['ALTER TABLE "LeaderboardEntry" ADD COLUMN "playerId$reference" TEXT GENERATED ALWAYS AS (NULLIF("playerId", '''')) STORED;', 'ALTER TABLE "LeaderboardEntry" ADD CONSTRAINT "fk_LeaderboardEntry_playerId" FOREIGN KEY ("playerId$reference") REFERENCES "Player" ("id") DEFERRABLE INITIALLY IMMEDIATE NOT VALID;', 'CREATE INDEX "ix_LeaderboardEntry_playerId" ON "LeaderboardEntry" ("playerId$reference");']::text[]);
SELECT pg_temp.add_missing_column('LeaderboardEntry', 'gameId$reference', ARRAY['ALTER TABLE "LeaderboardEntry" ADD COLUMN "gameId$reference" TEXT GENERATED ALWAYS AS (NULLIF("gameId", '''')) STORED;', 'ALTER TABLE "LeaderboardEntry" ADD CONSTRAINT "fk_LeaderboardEntry_gameId" FOREIGN KEY ("gameId$reference") REFERENCES "GameType" ("id") DEFERRABLE INITIALLY IMMEDIATE NOT VALID;', 'CREATE INDEX "ix_LeaderboardEntry_gameId" ON "LeaderboardEntry" ("gameId$reference");']::text[]);
SELECT pg_temp.add_missing_column('Match', 'gameId$reference', ARRAY['ALTER TABLE "Match" ADD COLUMN "gameId$reference" TEXT GENERATED ALWAYS AS (NULLIF("gameId", '''')) STORED;', 'ALTER TABLE "Match" ADD CONSTRAINT "fk_Match_gameId" FOREIGN KEY ("gameId$reference") REFERENCES "GameType" ("id") DEFERRABLE INITIALLY IMMEDIATE NOT VALID;', 'CREATE INDEX "ix_Match_gameId" ON "Match" ("gameId$reference");']::text[]);
SELECT pg_temp.add_missing_column('Match', 'playerOneId$reference', ARRAY['ALTER TABLE "Match" ADD COLUMN "playerOneId$reference" TEXT GENERATED ALWAYS AS (NULLIF("playerOneId", '''')) STORED;', 'ALTER TABLE "Match" ADD CONSTRAINT "fk_Match_playerOneId" FOREIGN KEY ("playerOneId$reference") REFERENCES "Player" ("id") DEFERRABLE INITIALLY IMMEDIATE NOT VALID;', 'CREATE INDEX "ix_Match_playerOneId" ON "Match" ("playerOneId$reference");']::text[]);
SELECT pg_temp.add_missing_column('Match', 'playerTwoId$reference', ARRAY['ALTER TABLE "Match" ADD COLUMN "playerTwoId$reference" TEXT GENERATED ALWAYS AS (NULLIF("playerTwoId", '''')) STORED;', 'ALTER TABLE "Match" ADD CONSTRAINT "fk_Match_playerTwoId" FOREIGN KEY ("playerTwoId$reference") REFERENCES "Player" ("id") DEFERRABLE INITIALLY IMMEDIATE NOT VALID;', 'CREATE INDEX "ix_Match_playerTwoId" ON "Match" ("playerTwoId$reference");']::text[]);
